apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pg_upgrade.yaml

configMapGenerator:
  - name: sharedx-pg-upgrade-entrypoints
    files:
      - entrypoints.sh

generatorOptions:
  disableNameSuffixHash: true
